#include "CustomerInterface.h"
#include "SpeedCurve.h"
#include "Common.h"


#define DEF_USE_GEELY     0
#if (DEF_USE_GEELY==1)

const unsigned int SPEEDCURVETABLE_CUSTOMER[SPEEDCURVETABLE_LENGTH] = 
{	
	// table of the geely SC02 speed-curve.
	// input: dutycycle from 0~100% with 128 accurancy

	//Table value	Comments		high	low active
	#if PAR_PROJECTS_SELECTION == GEELY_SS11_600W
	0	, //	0 =	0.00%	100.00%
	0	, //	1 =	0.78%	99.22%
	0	, //	2 =	1.56%	98.44%
	0	, //	3 =	2.34%	97.66%
	0	, //	4 =	3.13%	96.87%
	0	, //	5 =	3.91%	96.09%
	#else
	(unsigned int)(PAR_SYSTEM_SPEED_NOMINAL_RPM)	, //	0 =	0.00%	100.00%
	(unsigned int)(PAR_SYSTEM_SPEED_NOMINAL_RPM)	, //	1 =	0.78%	99.22%
	(unsigned int)(PAR_SYSTEM_SPEED_NOMINAL_RPM)	, //	2 =	1.56%	98.44%
	(unsigned int)(PAR_SYSTEM_SPEED_NOMINAL_RPM)	, //	3 =	2.34%	97.66%
	(unsigned int)(PAR_SYSTEM_SPEED_NOMINAL_RPM)	, //	4 =	3.13%	96.87%
	(unsigned int)(PAR_SYSTEM_SPEED_NOMINAL_RPM)	, //	5 =	3.91%	96.09%
	#endif
	(unsigned int)(PAR_SYSTEM_SPEED_NOMINAL_RPM)	, //	6 =	4.69%	95.31%
	(unsigned int)(PAR_SYSTEM_SPEED_NOMINAL_RPM)	, //	7 =	5.47%	94.53%
	(unsigned int)(PAR_SYSTEM_SPEED_NOMINAL_RPM)	, //	8 =	6.25%	93.75%
	(unsigned int)(PAR_SYSTEM_SPEED_NOMINAL_RPM)	, //	9 =	7.03%	92.97%
	(unsigned int)(PAR_SYSTEM_SPEED_NOMINAL_RPM)	, //	10 =	7.81%	92.19%
	(unsigned int)(PAR_SYSTEM_SPEED_NOMINAL_RPM)	, //	11 =	8.59%	91.41%
	(unsigned int)(PAR_SYSTEM_SPEED_NOMINAL_RPM)	, //	12 =	9.38%	90.62%
	(unsigned int)(PAR_SYSTEM_SPEED_NOMINAL_RPM)	, //	13 =	10.16%	89.84%
	(unsigned int)(PAR_SYSTEM_SPEED_NOMINAL_RPM)	, //	14 =	10.94%	89.06%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(112-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	15 =	11.72%	88.28%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(111-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	16 =	12.50%	87.50%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(110-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	17 =	13.28%	86.72%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(109-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	18 =	14.06%	85.94%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(108-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	19 =	14.84%	85.16%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(107-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	20 =	15.63%	84.37%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(106-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	21 =	16.41%	83.59%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(105-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	22 =	17.19%	82.81%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(104-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	23 =	17.97%	82.03%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(103-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	24 =	18.75%	81.25%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(102-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	25 =	19.53%	80.47%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(101-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	26 =	20.31%	79.69%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(100-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	27 =	21.09%	78.91%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(99-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	28 =	21.88%	78.12%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(98-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	29 =	22.66%	77.34%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(97-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	30 =	23.44%	76.56%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(96-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	31 =	24.22%	75.78%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(95-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	32 =	25.00%	75.00%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(94-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	33 =	25.78%	74.22%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(93-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	34 =	26.56%	73.44%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(92-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	35 =	27.34%	72.66%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(91-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	36 =	28.13%	71.87%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(90-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	37 =	28.91%	71.09%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(89-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	38 =	29.69%	70.31%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(88-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	39 =	30.47%	69.53%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(87-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	40 =	31.25%	68.75%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(86-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	41 =	32.03%	67.97%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(85-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	42 =	32.81%	67.19%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(84-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	43 =	33.59%	66.41%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(83-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	44 =	34.38%	65.62%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(82-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	45 =	35.16%	64.84%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(81-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	46 =	35.94%	64.06%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(80-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	47 =	36.72%	63.28%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(79-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	48 =	37.50%	62.50%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(78-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	49 =	38.28%	61.72%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(77-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	50 =	39.06%	60.94%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(76-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	51 =	39.84%	60.16%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(75-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	52 =	40.63%	59.37%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(74-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	53 =	41.41%	58.59%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(73-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	54 =	42.19%	57.81%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(72-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	55 =	42.97%	57.03%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(71-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	56 =	43.75%	56.25%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(70-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	57 =	44.53%	55.47%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(69-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	58 =	45.31%	54.69%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(68-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	59 =	46.09%	53.91%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(67-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	60 =	46.88%	53.12%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(66-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	61 =	47.66%	52.34%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(65-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	62 =	48.44%	51.56%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(64-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	63 =	49.22%	50.78%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(63-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	64 =	50.00%	50.00%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(62-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	65 =	50.78%	49.22%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(61-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	66 =	51.56%	48.44%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(60-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	67 =	52.34%	47.66%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(59-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	68 =	53.13%	46.87%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(58-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	69 =	53.91%	46.09%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(57-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	70 =	54.69%	45.31%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(56-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	71 =	55.47%	44.53%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(55-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	72 =	56.25%	43.75%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(54-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	73 =	57.03%	42.97%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(53-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	74 =	57.81%	42.19%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(52-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	75 =	58.59%	41.41%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(51-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	76 =	59.38%	40.62%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(50-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	77 =	60.16%	39.84%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(49-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	78 =	60.94%	39.06%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(48-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	79 =	61.72%	38.28%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(47-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	80 =	62.50%	37.50%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(46-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	81 =	63.28%	36.72%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(45-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	82 =	64.06%	35.94%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(44-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	83 =	64.84%	35.16%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(43-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	84 =	65.63%	34.37%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(42-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	85 =	66.41%	33.59%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(41-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	86 =	67.19%	32.81%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(40-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	87 =	67.97%	32.03%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(39-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	88 =	68.75%	31.25%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(38-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	89 =	69.53%	30.47%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(37-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	90 =	70.31%	29.69%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(36-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	91 =	71.09%	28.91%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(35-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	92 =	71.88%	28.12%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(34-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	93 =	72.66%	27.34%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(33-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	94 =	73.44%	26.56%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(32-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	95 =	74.22%	25.78%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(31-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	96 =	75.00%	25.00%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(30-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	97 =	75.78%	24.22%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(29-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	98 =	76.56%	23.44%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(28-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	99 =	77.34%	22.66%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(27-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	100 =	78.13%	21.87%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(26-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	101 =	78.91%	21.09%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(25-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	102 =	79.69%	20.31%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(24-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	103 =	80.47%	19.53%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(23-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	104 =	81.25%	18.75%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(22-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	105 =	82.03%	17.97%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(21-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	106 =	82.81%	17.19%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(20-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	107 =	83.59%	16.41%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(19-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	108 =	84.38%	15.62%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(18-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	109 =	85.16%	14.84%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(17-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	110 =	85.94%	14.06%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(16-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	111 =	86.72%	13.28%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(15-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	112 =	87.50%	12.50%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(14-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	113 =	88.28%	11.72%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(13-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	114 =	89.06%	10.94%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(12-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	115 =	89.84%	10.16%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(11-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	116 =	90.63%	9.37%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(10-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	117 =	91.41%	8.59%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(9-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	118 =	92.19%	7.81%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(8-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	119 =	92.97%	7.03%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM)	, //	120 =	93.75%	6.25%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM)	, //	121 =	94.53%	5.47%
	0	, //	122 =	95.31%	4.69%
	0	, //	123 =	96.09%	3.91%
	0	, //	124 =	96.88%	3.12%
	0	, //	125 =	97.66%	2.34%
	0	, //	126 =	98.44%	1.56%
	0	 //	127 =	99.22%	0.78%

};

#endif
