#include "CustomerInterface.h"
#include "SpeedCurve.h"
#include "Common.h"


#define DEF_USE_Platform   1
#if (DEF_USE_Platform==1)
		
const unsigned int SPEEDCURVETABLE_CUSTOMER[SPEEDCURVETABLE_LENGTH] = 
{	
	//Table value	Comments		high
	0 ,// enter into sleep when KL15 off, or nominal running if KL15 on, after 10s	, //	0 =	0.00%
	0 ,// stop when KL15 off, or nominal running if KL15 on, after 10s	, //	1 =	0.78%
	0 ,// stop when KL15 off, or nominal running if KL15 on, after 10s	, //	2 =	1.56%
	0 ,// stop when KL15 off, or nominal running if KL15 on, after 10s	, //	3 =	2.34%
	0 ,// stop when KL15 off, or nominal running if KL15 on, after 10s	, //	4 =	3.13%
	0 ,// stop when KL15 off, or nominal running if KL15 on, after 10s	, //	5 =	3.91%
	0 ,// stop when KL15 off, or nominal running if KL15 on, after 10s	, //	6 =	4.69%
	0	, //	7 =	5.47%
	0	, //	8 =	6.25%
	0	, //	9 =	7.03%
	0	, //	10 =	7.81%
	0	, //	11 =	8.59%
	0	, //	12 =	9.38%
	0	, //	13 =	10.16%
	0	, //	14 =	10.94%
	0	, //	15 =	11.72%
	0	, //	16 =	12.50%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM)	, //	17 =	13.28%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM)	, //	18 =	14.06%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM)	, //	19 =	14.84%
#if PAR_MOTOR_SELECTION == MOTOR_PLATFORM_400W	
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM)	, //	20 =	15.63%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM)	, //	21 =	16.41%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM)	, //	22 =	17.19%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM)	, //	23 =	17.97%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM)	, //	24 =	18.75%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM)	, //	25 =	19.53%
#else		
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(20-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	20 =	15.63%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(21-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	21 =	16.41%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(22-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	22 =	17.19%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(23-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	23 =	17.97%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(24-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	24 =	18.75%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(25-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	25 =	19.53%
#endif	
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(26-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	26 =	20.31%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(27-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	27 =	21.09%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(28-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	28 =	21.88%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(29-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	29 =	22.66%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(30-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	30 =	23.44%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(31-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	31 =	24.22%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(32-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	32 =	25.00%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(33-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	33 =	25.78%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(34-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	34 =	26.56%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(35-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	35 =	27.34%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(36-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	36 =	28.13%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(37-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	37 =	28.91%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(38-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	38 =	29.69%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(39-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	39 =	30.47%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(40-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	40 =	31.25%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(41-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	41 =	32.03%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(42-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	42 =	32.81%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(43-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	43 =	33.59%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(44-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	44 =	34.38%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(45-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	45 =	35.16%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(46-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	46 =	35.94%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(47-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	47 =	36.72%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(48-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	48 =	37.50%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(49-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	49 =	38.28%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(50-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	50 =	39.06%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(51-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	51 =	39.84%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(52-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	52 =	40.63%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(53-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	53 =	41.41%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(54-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	54 =	42.19%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(55-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	55 =	42.97%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(56-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	56 =	43.75%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(57-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	57 =	44.53%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(58-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	58 =	45.31%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(59-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	59 =	46.09%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(60-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	60 =	46.88%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(61-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	61 =	47.66%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(62-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	62 =	48.44%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(63-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	63 =	49.22%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(64-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	64 =	50.00%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(65-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	65 =	50.78%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(66-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	66 =	51.56%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(67-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	67 =	52.34%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(68-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	68 =	53.13%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(69-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	69 =	53.91%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(70-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	70 =	54.69%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(71-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	71 =	55.47%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(72-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	72 =	56.25%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(73-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	73 =	57.03%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(74-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	74 =	57.81%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(75-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	75 =	58.59%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(76-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	76 =	59.38%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(77-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	77 =	60.16%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(78-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	78 =	60.94%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(79-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	79 =	61.72%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(80-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	80 =	62.50%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(81-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	81 =	63.28%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(82-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	82 =	64.06%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(83-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	83 =	64.84%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(84-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	84 =	65.63%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(85-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	85 =	66.41%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(86-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	86 =	67.19%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(87-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	87 =	67.97%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(88-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	88 =	68.75%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(89-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	89 =	69.53%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(90-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	90 =	70.31%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(91-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	91 =	71.09%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(92-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	92 =	71.88%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(93-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	93 =	72.66%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(94-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	94 =	73.44%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(95-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	95 =	74.22%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(96-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	96 =	75.00%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(97-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	97 =	75.78%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(98-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	98 =	76.56%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(99-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	99 =	77.34%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(100-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	100 =	78.13%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(101-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	101 =	78.91%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(102-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	102 =	79.69%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(103-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	103 =	80.47%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(104-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	104 =	81.25%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(105-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	105 =	82.03%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(106-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	106 =	82.81%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(107-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	107 =	83.59%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(108-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	108 =	84.38%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(109-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	109 =	85.16%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(110-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	110 =	85.94%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(111-PAR_SYSTEM_PWMDUTY_INDEX_MIN)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX-PAR_SYSTEM_PWMDUTY_INDEX_MIN)))	, //	111 =	86.72%
	(unsigned int)(PAR_SYSTEM_SPEED_NOMINAL_RPM)	, //	112 =	87.50%
	(unsigned int)(PAR_SYSTEM_SPEED_NOMINAL_RPM)	, //	113 =	88.28%
	(unsigned int)(PAR_SYSTEM_SPEED_NOMINAL_RPM)	, //	114 =	89.06%
	(unsigned int)(PAR_SYSTEM_SPEED_NOMINAL_RPM)	, //	115 =	89.84%
	(unsigned int)(PAR_SYSTEM_SPEED_NOMINAL_RPM)	, //	116 =	90.63%
	(unsigned int)(PAR_SYSTEM_SPEED_NOMINAL_RPM)	, //	117 =	91.41%
	(unsigned int)(PAR_SYSTEM_SPEED_NOMINAL_RPM)	, //	118 =	92.19%
	(unsigned int)(PAR_SYSTEM_SPEED_NOMINAL_RPM)	, //	119 =	92.97%
	(unsigned int)(PAR_SYSTEM_SPEED_NOMINAL_RPM)	, //	120 =	93.75%
	(unsigned int)(PAR_SYSTEM_SPEED_NOMINAL_RPM)	, //	121 =	94.53%
	(unsigned int)(PAR_SYSTEM_SPEED_NOMINAL_RPM)	, //	122 =	95.31%
	0 ,// stop when KL15 off, or nominal running if KL15 on, after 10s	, //	123 =	96.09%
	0 ,// stop when KL15 off, or nominal running if KL15 on, after 10s	, //	124 =	96.88%
	0 ,// stop when KL15 off, or nominal running if KL15 on, after 10s	, //	125 =	97.66%
	0 ,// stop when KL15 off, or nominal running if KL15 on, after 10s	, //	126 =	98.44%
	0 // stop when KL15 off, or nominal running if KL15 on, after 10s	 //	127 =	99.22%
};
#endif

#define PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE 10
#define PAR_SYSTEM_PWMDUTY_INDEX_MAX_LINTABLE 90
const unsigned int SPEEDCURVETABLE_LIN[SPEEDCURVETABLE_LENGTH] = 
{		
	//Table value	Comments			
	0	, //	0 =	0	%
	0	, //	1 =	1	%
	0	, //	2 =	2	%
	0	, //	3 =	3	%
	0	, //	4 =	4	%
	0	, //	5 =	5	%
	0	, //	6 =	6	%
	0	, //	7 =	7	%
	0	, //	8 =	8	%
	0	, //	9 =	9	%
  (unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(10-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX_LINTABLE-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)))	, //	10 =	10	%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(11-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX_LINTABLE-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)))	, //	11 =	11	%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(12-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX_LINTABLE-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)))	, //	12 =	12	%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(13-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX_LINTABLE-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)))	, //	13 =	13	%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(14-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX_LINTABLE-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)))	, //	14 =	14	%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(15-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX_LINTABLE-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)))	, //	15 =	15	%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(16-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX_LINTABLE-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)))	, //	16 =	16	%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(17-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX_LINTABLE-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)))	, //	17 =	17	%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(18-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX_LINTABLE-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)))	, //	18 =	18	%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(19-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX_LINTABLE-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)))	, //	19 =	19	%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(20-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX_LINTABLE-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)))	, //	20 =	20	%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(21-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX_LINTABLE-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)))	, //	21 =	21	%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(22-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX_LINTABLE-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)))	, //	22 =	22	%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(23-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX_LINTABLE-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)))	, //	23 =	23	%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(24-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX_LINTABLE-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)))	, //	24 =	24	%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(25-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX_LINTABLE-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)))	, //	25 =	25	%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(26-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX_LINTABLE-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)))	, //	26 =	26	%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(27-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX_LINTABLE-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)))	, //	27 =	27	%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(28-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX_LINTABLE-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)))	, //	28 =	28	%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(29-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX_LINTABLE-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)))	, //	29 =	29	%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(30-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX_LINTABLE-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)))	, //	30 =	30	%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(31-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX_LINTABLE-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)))	, //	31 =	31	%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(32-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX_LINTABLE-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)))	, //	32 =	32	%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(33-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX_LINTABLE-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)))	, //	33 =	33	%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(34-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX_LINTABLE-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)))	, //	34 =	34	%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(35-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX_LINTABLE-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)))	, //	35 =	35	%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(36-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX_LINTABLE-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)))	, //	36 =	36	%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(37-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX_LINTABLE-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)))	, //	37 =	37	%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(38-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX_LINTABLE-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)))	, //	38 =	38	%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(39-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX_LINTABLE-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)))	, //	39 =	39	%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(40-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX_LINTABLE-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)))	, //	40 =	40	%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(41-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX_LINTABLE-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)))	, //	41 =	41	%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(42-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX_LINTABLE-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)))	, //	42 =	42	%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(43-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX_LINTABLE-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)))	, //	43 =	43	%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(44-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX_LINTABLE-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)))	, //	44 =	44	%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(45-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX_LINTABLE-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)))	, //	45 =	45	%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(46-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX_LINTABLE-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)))	, //	46 =	46	%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(47-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX_LINTABLE-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)))	, //	47 =	47	%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(48-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX_LINTABLE-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)))	, //	48 =	48	%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(49-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX_LINTABLE-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)))	, //	49 =	49	%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(50-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX_LINTABLE-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)))	, //	50 =	50	%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(51-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX_LINTABLE-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)))	, //	51 =	51	%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(52-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX_LINTABLE-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)))	, //	52 =	52	%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(53-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX_LINTABLE-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)))	, //	53 =	53	%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(54-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX_LINTABLE-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)))	, //	54 =	54	%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(55-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX_LINTABLE-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)))	, //	55 =	55	%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(56-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX_LINTABLE-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)))	, //	56 =	56	%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(57-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX_LINTABLE-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)))	, //	57 =	57	%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(58-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX_LINTABLE-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)))	, //	58 =	58	%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(59-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX_LINTABLE-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)))	, //	59 =	59	%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(60-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX_LINTABLE-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)))	, //	60 =	60	%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(61-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX_LINTABLE-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)))	, //	61 =	61	%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(62-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX_LINTABLE-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)))	, //	62 =	62	%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(63-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX_LINTABLE-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)))	, //	63 =	63	%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(64-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX_LINTABLE-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)))	, //	64 =	64	%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(65-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX_LINTABLE-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)))	, //	65 =	65	%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(66-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX_LINTABLE-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)))	, //	66 =	66	%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(67-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX_LINTABLE-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)))	, //	67 =	67	%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(68-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX_LINTABLE-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)))	, //	68 =	68	%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(69-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX_LINTABLE-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)))	, //	69 =	69	%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(70-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX_LINTABLE-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)))	, //	70 =	70	%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(71-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX_LINTABLE-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)))	, //	71 =	71	%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(72-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX_LINTABLE-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)))	, //	72 =	72	%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(73-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX_LINTABLE-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)))	, //	73 =	73	%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(74-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX_LINTABLE-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)))	, //	74 =	74	%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(75-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX_LINTABLE-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)))	, //	75 =	75	%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(76-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX_LINTABLE-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)))	, //	76 =	76	%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(77-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX_LINTABLE-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)))	, //	77 =	77	%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(78-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX_LINTABLE-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)))	, //	78 =	78	%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(79-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX_LINTABLE-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)))	, //	79 =	79	%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(80-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX_LINTABLE-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)))	, //	80 =	80	%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(81-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX_LINTABLE-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)))	, //	81 =	81	%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(82-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX_LINTABLE-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)))	, //	82 =	82	%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(83-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX_LINTABLE-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)))	, //	83 =	83	%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(84-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX_LINTABLE-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)))	, //	84 =	84	%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(85-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX_LINTABLE-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)))	, //	85 =	85	%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(86-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX_LINTABLE-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)))	, //	86 =	86	%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(87-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX_LINTABLE-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)))	, //	87 =	87	%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(88-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX_LINTABLE-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)))	, //	88 =	88	%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(89-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX_LINTABLE-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)))	, //	89 =	89	%
	(unsigned int)(PAR_SYSTEM_SPEED_MIN_RPM+(((long)(90-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)*(PAR_SYSTEM_SPEED_NOMINAL_RPM-PAR_SYSTEM_SPEED_MIN_RPM))/(PAR_SYSTEM_PWMDUTY_INDEX_MAX_LINTABLE-PAR_SYSTEM_PWMDUTY_INDEX_MIN_LINTABLE)))	, //	90 =	90	%
	(unsigned int)(PAR_SYSTEM_SPEED_NOMINAL_RPM)	, //	91 =	91	%
	(unsigned int)(PAR_SYSTEM_SPEED_NOMINAL_RPM)	, //	92 =	92	%
	(unsigned int)(PAR_SYSTEM_SPEED_NOMINAL_RPM)	, //	93 =	93	%
	(unsigned int)(PAR_SYSTEM_SPEED_NOMINAL_RPM)	, //	94 =	94	%
	(unsigned int)(PAR_SYSTEM_SPEED_MAX_RPM)	, //	95 =	95	%
	(unsigned int)(PAR_SYSTEM_SPEED_MAX_RPM)	, //	96 =	96	%
	(unsigned int)(PAR_SYSTEM_SPEED_MAX_RPM)	, //	97 =	97	%
	(unsigned int)(PAR_SYSTEM_SPEED_MAX_RPM)	, //	98 =	98	%
	(unsigned int)(PAR_SYSTEM_SPEED_MAX_RPM)	, //	99 =	99	%
	(unsigned int)(PAR_SYSTEM_SPEED_MAX_RPM)	, //	100 =	100	%
	(unsigned int)(PAR_SYSTEM_SPEED_MAX_RPM)	, //	101 =	101	%
	(unsigned int)(PAR_SYSTEM_SPEED_MAX_RPM)	, //	102 =	102	%
	(unsigned int)(PAR_SYSTEM_SPEED_MAX_RPM)	, //	103 =	103	%
	(unsigned int)(PAR_SYSTEM_SPEED_MAX_RPM)	, //	104 =	104	%
	(unsigned int)(PAR_SYSTEM_SPEED_MAX_RPM)	, //	105 =	105	%
	(unsigned int)(PAR_SYSTEM_SPEED_MAX_RPM)	, //	106 =	106	%
	(unsigned int)(PAR_SYSTEM_SPEED_MAX_RPM)	, //	107 =	107	%
	(unsigned int)(PAR_SYSTEM_SPEED_MAX_RPM)	, //	108 =	108	%
	(unsigned int)(PAR_SYSTEM_SPEED_MAX_RPM)	, //	109 =	109	%
	(unsigned int)(PAR_SYSTEM_SPEED_MAX_RPM)	, //	110 =	110	%
	(unsigned int)(PAR_SYSTEM_SPEED_MAX_RPM)	, //	111 =	111	%
	(unsigned int)(PAR_SYSTEM_SPEED_MAX_RPM)	, //	112 =	112	%
	(unsigned int)(PAR_SYSTEM_SPEED_MAX_RPM)	, //	113 =	113	%
	(unsigned int)(PAR_SYSTEM_SPEED_MAX_RPM)	, //	114 =	114	%
	(unsigned int)(PAR_SYSTEM_SPEED_MAX_RPM)	, //	115 =	115	%
	(unsigned int)(PAR_SYSTEM_SPEED_MAX_RPM)	, //	116 =	116	%
	(unsigned int)(PAR_SYSTEM_SPEED_MAX_RPM)	, //	117 =	117	%
	(unsigned int)(PAR_SYSTEM_SPEED_MAX_RPM)	, //	118 =	118	%
	(unsigned int)(PAR_SYSTEM_SPEED_MAX_RPM)	, //	119 =	119	%
	(unsigned int)(PAR_SYSTEM_SPEED_MAX_RPM)	, //	120 =	120	%
	(unsigned int)(PAR_SYSTEM_SPEED_MAX_RPM)	, //	121 =	121	%
	(unsigned int)(PAR_SYSTEM_SPEED_MAX_RPM)	, //	122 =	122	%
	(unsigned int)(PAR_SYSTEM_SPEED_MAX_RPM)	, //	123 =	123	%
	(unsigned int)(PAR_SYSTEM_SPEED_MAX_RPM)	, //	124 =	124	%
	(unsigned int)(PAR_SYSTEM_SPEED_MAX_RPM)	, //	125 =	125	%
	(unsigned int)(PAR_SYSTEM_SPEED_MAX_RPM)	, //	126 =	126	%
	(unsigned int)(0)	 //	127 =	127	%
};


unsigned int GetSpeedByDigital(unsigned char speeddigital, unsigned char uctableselect)
{
	unsigned int speedreturn = INIT;

	if(uctableselect==SPEEDCURVETABLE_TYPE_CUSTOMER)
	{
		if(speeddigital>127)
		{
			speedreturn = INIT;
		}
		else
		{
			speedreturn = SPEEDCURVETABLE_CUSTOMER[speeddigital];
		}
	}
	else
	{
		speedreturn = SPEEDCURVETABLE_LIN[speeddigital];
	}	
	
    return speedreturn;
}




